# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('email_user', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user_message',
            },
        ),
    ]
