# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180306_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.Phone'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
