# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180306_1900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phone',
            table='phone',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
