# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180306_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Phone'),
        ),
    ]
