# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 19:40
from __future__ import unicode_literals
from random import randint
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20180306_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user',
        ),
        migrations.AddField(
            model_name='userphone',
            name='user_profile',
            field=models.OneToOneField(default="1", on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Role'),
        ),
    ]
