# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0009_auto_20180306_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userphone',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
