# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorites',
            unique_together=set([('user', 'house')]),
        ),
    ]
