# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20180310_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userphone', to=settings.AUTH_USER_MODEL),
        ),
    ]
