# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20180315_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorites', to='buildings.House'),
        ),
    ]
