# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('image_url', models.ImageField(upload_to=b'')),
                ('price', models.IntegerField()),
                ('bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.SmallIntegerField(blank=True, null=True)),
                ('area', models.SmallIntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('garage', models.SmallIntegerField()),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.House')),
            ],
            options={
                'db_table': 'houses_details',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.ImageField(upload_to=b'')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.House')),
            ],
            options={
                'db_table': 'houses_image',
            },
        ),
    ]
