# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 2, 11, 11, 44, 16, 898333, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
