# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='countroom',
            new_name='bathrooms',
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
    ]
