# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 19:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'houses_visited',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housedetails',
            name='year_built',
            field=models.DateField(default=datetime.datetime(2018, 2, 20, 19, 25, 28, 577647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='housevisited',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='housevisited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
