# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
