# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20180215_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
