# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_housedetails_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseimage', to='buildings.House'),
        ),
        migrations.AlterUniqueTogether(
            name='housevisited',
            unique_together=set([('user', 'house')]),
        ),
    ]
