# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_housedetails_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='housevisited',
            unique_together=set([('user', 'house')]),
        ),
    ]
