# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_house_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
    ]
