# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_house_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House')),
            ],
        ),
    ]
