# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20180308_1030'),
        ('buildings', '0008_remove_house_location'),
    ]

    operations = [
    ]
