# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 19:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House')),
            ],
            options={
                'db_table': 'houses_location',
            },
        ),
    ]
