# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 10:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('FR', 'For Rent'), ('RS', 'For Sale')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='houselocation',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='houselocation', to='buildings.House'),
        ),
    ]
