# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.IntegerField()),
                ('location', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('FR', 'For Rent'), ('RS', 'For Sale')], default='FR', max_length=2),
        ),
    ]
