# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_houselocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('FR', 'For Rent'), ('RS', 'For Sale')], default='FR', max_length=2),
        ),
    ]
