# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-15 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0010_auto_20180315_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housefavorites', to='buildings.House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housefavorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'house_favorites',
            },
        ),
        migrations.AlterUniqueTogether(
            name='housefavorites',
            unique_together=set([('user', 'house')]),
        ),
    ]
