# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 19:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20180313_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
