# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_auto_20180314_1935'),
        ('buildings', '0010_auto_20180313_1905'),
    ]

    operations = [
    ]
